# permissions for end users to view certinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certinfo-viewer-role
rules:
- apiGroups:
  - cert.vault.com
  resources:
  - certinfoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert.vault.com
  resources:
  - certinfoes/status
  verbs:
  - get
